In [36]:
"""Problem 1: Employee Salary Analysis"""

import pandas as pd
import os
data = {
    "name": ["MR.A", "MR.B", "MR.C", "MR.D", "MR.E", "MR.F", "MR.G", "MR.H"],
    "age": [25, 30, 35, 40, 29, 33, 27, 31],
    "salary": [50000, 60000, 70000, 80000, 55000, 65000, 72000, 58000],
    "department": ["HR", "IT", "IT", "Finance", "HR", "Finance", "IT", "HR"]
}
df = pd.DataFrame(data)
df.to_csv("employees_large.csv", index=False)
print("Sample employees_large.csv file created successfully!")

if "employees_large.csv" in os.listdir():
    print("File found! Proceeding with analysis.")
else:
    print("Error: File not found!")

df_employees = pd.read_csv('employees_large.csv')

average_salary = df_employees.groupby('department')['salary'].mean()
print("Average Salary by Department:\n", average_salary)

highest_salary_department = average_salary.idxmax()
print("Department with Highest Average Salary:", highest_salary_department)

Sample employees_large.csv file created successfully!
File found! Proceeding with analysis.
Average Salary by Department:
 department
Finance    72500.000000
HR         54333.333333
IT         67333.333333
Name: salary, dtype: float64
Department with Highest Average Salary: Finance

In [39]:
"""Problem 2: Sales Data Analysis"""
import pandas as pd
import os


if "sales_large.csv" not in os.listdir():
    sales_data = {
        "region": ["North", "South", "East", "West", "North", "South", "East", "West"],
        "product": ["A", "B", "C", "A", "B", "C", "A", "B"],
        "sales": [1000, 1500, 1200, 1700, 1800, 1600, 1400, 1300]
    }

    df_sales = pd.DataFrame(sales_data)
    df_sales.to_csv("sales_large.csv", index=False)
    print("\nSample sales_large.csv file created successfully!")

df_sales = pd.read_csv('sales_large.csv')

total_sales = df_sales.groupby(['region', 'product'])['sales'].sum()
print("\nTotal Sales by Region and Product:\n", total_sales)

top_product = df_sales.groupby('product')['sales'].sum().idxmax()
print("\nProduct with Highest Total Sales:", top_product)

Total Sales by Region and Product:
 region  product
East    A          1400
        C          1200
North   A          1000
        B          1800
South   B          1500
        C          1600
West    A          1700
        B          1300
Name: sales, dtype: int64

Product with Highest Total Sales: B

In [20]:
"""Problem 3: Matrix Operations with NumPy"""

import numpy as np

A = np.array([[2,4,6], [1,3,5], [7,9,11]])
B = np.array([[8,5, 2], [7,4,1], [6,3,0]])
sum_matrix = A + B
product_matrix= A * B
print("Sum of matrices:")
print(sum_matrix)
print("Product of matrices:")
print(product_matrix)

B_transpose = B.T
result = np.dot(A, B_transpose)
print("Result of A * B^T:")
print(result)
determinant = np.linalg.det(A)
print("Determinant of the matrix A:", determinant)

Sum of matrices:
[[10  9  8]
 [ 8  7  6]
 [13 12 11]]
Product of matrices:
[[16 20 12]
 [ 7 12  5]
 [42 27  0]]
Result of A * B^T:
[[ 48  36  24]
 [ 33  24  15]
 [123  96  69]]
Determinant of the matrix A: 0.0

In [21]:
"""Problem 4: Statistical Analysis of Random Dataset"""

data = np.random.randn(10000)

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)
print(f"Mean: {mean_val}, Median: {median_val}, Standard Deviation: {std_dev}")

min_val, max_val = np.min(data), np.max(data)
print(f"Minimum: {min_val}, Maximum: {max_val}")

count_greater_mean = np.sum(data > mean_val)
print(f"Count of values greater than mean: {count_greater_mean}")

data_normalized = (data - min_val) / (max_val - min_val)
print("First 10 normalized values:", data_normalized[:10])

Mean: 0.017299217348465908, Median: 0.02855411304976469, Standard Deviation: 1.0168177968992445
Minimum: -4.690701427108116, Maximum: 3.6536975035914208
Count of values greater than mean: 5038
First 10 normalized values: [0.50028586 0.4574028  0.52329568 0.54028679 0.86411138 0.49850158
 0.57204871 0.98036385 0.68293649 0.67469116]

In [16]:
"""Problem 5: List Comprehension with Temperature Data"""

temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]

above_32 = [temp for temp in temperatures if temp > 32]
print("Temperatures above 32°C:", above_32)

classified_temps = [(temp, "Hot" if temp > 35 else "Warm" if 30 <= temp <= 35 else "Cool") for temp in temperatures]
print("Classified Temperatures:", classified_temps)

avg_temp = sum(temperatures) / len(temperatures)
temp_differences = [temp - avg_temp for temp in temperatures]
print("Temperature Differences from Monthly Average:", temp_differences)

Temperatures above 32°C: [35, 33, 36, 34, 37, 38, 35, 33, 36, 34, 35, 33]
Classified Temperatures: [(28, 'Cool'), (32, 'Warm'), (35, 'Warm'), (31, 'Warm'), (29, 'Cool'), (30, 'Warm'), (33, 'Warm'), (36, 'Hot'), (27, 'Cool'), (25, 'Cool'), (34, 'Warm'), (30, 'Warm'), (29, 'Cool'), (37, 'Hot'), (38, 'Hot'), (26, 'Cool'), (31, 'Warm'), (35, 'Warm'), (33, 'Warm'), (32, 'Warm'), (36, 'Hot'), (34, 'Warm'), (29, 'Cool'), (28, 'Cool'), (27, 'Cool'), (35, 'Warm'), (32, 'Warm'), (30, 'Warm'), (31, 'Warm'), (33, 'Warm')]
Temperature Differences from Monthly Average: [-3.533333333333335, 0.466666666666665, 3.466666666666665, -0.533333333333335, -2.533333333333335, -1.533333333333335, 1.466666666666665, 4.466666666666665, -4.533333333333335, -6.533333333333335, 2.466666666666665, -1.533333333333335, -2.533333333333335, 5.466666666666665, 6.466666666666665, -5.533333333333335, -0.533333333333335, 3.466666666666665, 1.466666666666665, 0.466666666666665, 4.466666666666665, 2.466666666666665, -2.533333333333335, -3.533333333333335, -4.533333333333335, 3.466666666666665, 0.466666666666665, -1.533333333333335, -0.533333333333335, 1.466666666666665]